import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync, writeFileSync, existsSync, mkdirSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store, RunLock } from '../src/store.ts';
import { iso, type RecordData, type Attachment } from '../src/model.ts';
import { dateBounds, exportJsonl } from '../src/export.ts';
import { loadConfig, id, type Config } from '../src/config.ts';
import { Attachments, safePath, cdnUrl, media } from '../src/attachments.ts';
import { inScope, acceptAuthor } from '../src/bot.ts';

const guild = '123456789012345678', channel = '223456789012345678';
const attachment: Attachment = { attachment_id: '423456789012345678', filename: 'image.png', content_type: 'image/png', size: 4, url: 'https://cdn.discordapp.com/attachments/test.png' };
function record(overrides: Partial<RecordData> = {}): RecordData { return { guild_id: guild, channel_id: channel, message_id: '323456789012345678', content: 'original', created_at: iso('2026-09-14T01:00:00Z'), edited_at: null, collected_at: iso(), jump_url: 'https://discord.com/channels/test', attachments: [attachment], ...overrides }; }
function fixture(t: { after(fn: () => void): void }) {
  const root = mkdtempSync(join(tmpdir(), 'telemetry-ts-')), db = new Store(join(root, 'test.sqlite3'), guild);
  t.after(() => { db.close(); rmSync(root, { recursive: true, force: true }); }); return { root, db };
}
function config(root: string, overrides: Partial<Config> = {}): Config { return { guild, token: 'test', channels: new Map([[channel, '開発']]), database: join(root, 'test.sqlite3'), attachments: join(root, 'attachments'), exports: join(root, 'exports'), maxBytes: 100, concurrency: 2, timeout: 1000, retries: 0, minFree: 0, includeBots: false, includeWebhooks: false, recoverySeconds: 300, controlMode: 'gateway', origin: 'http://localhost:8787', apiKey: '', ...overrides }; }

test('upsert is idempotent and preserves download state', t => { const { db } = fixture(t); db.upsert(record()); db.updateAttachment(attachment.attachment_id, { status: 'saved', path: 'x', attempts: 2 }); db.upsert(record()); assert.equal((db.status().messages[0]).count, 1); assert.equal(db.attachments(record().message_id)[0].status, 'saved'); assert.equal(db.attachments(record().message_id)[0].attempts, 2); });
test('sparse null edit keeps content and timestamp', t => { const { db } = fixture(t); db.upsert(record({ edited_at: iso('2026-09-14T02:00:00Z') })); db.patch(record().message_id, { edited_at: null }, iso('2026-09-15')); assert.equal(db.get(record().message_id)!.content, 'original'); assert.equal(db.get(record().message_id)!.edited_at, iso('2026-09-14T02:00:00Z')); });
test('in-flight history cannot undo an event even with equal revision', t => { const { db } = fixture(t); db.upsert(record(), iso('2026-09-14T02:00Z')); db.patch(record().message_id, { content: 'new' }, iso('2026-09-14T03:00Z')); assert.equal(db.upsert(record(), iso('2026-09-14T02:30Z')), false); assert.equal(db.get(record().message_id)!.content, 'new'); });
test('older edit revision is rejected even with a newer observation', t => { const { db } = fixture(t); db.upsert(record({ content: 'new', edited_at: iso('2026-09-14T05:00Z') })); assert.equal(db.upsert(record(), iso('2026-09-15')), false); });
test('microsecond revisions retain ordering and UTC offsets normalize', () => { assert.ok(iso('2026-09-14T00:00:00.000002Z') > iso('2026-09-14T00:00:00.000001Z')); assert.equal(iso('2026-09-14T09:00:00.123456+09:00'), '2026-09-14T00:00:00.123456+00:00'); });
test('deletion purges content and attachment references permanently', t => { const { db } = fixture(t); db.upsert(record()); db.delete(record().message_id, channel); db.upsert(record()); assert.equal(db.get(record().message_id)!.deleted, true); assert.equal(db.get(record().message_id)!.content, undefined); assert.deepEqual(db.attachments(record().message_id), []); assert.equal(db.cleanupPaths().length, 1); assert.ok(!JSON.stringify(db.get(record().message_id)).includes('original')); });
test('unknown tombstone blocks subsequent history', t => { const { db } = fixture(t); db.delete(record().message_id, channel); assert.equal(db.upsert(record()), false); });
test('attachment removal queues cleanup and cannot change owner', t => { const { db } = fixture(t); db.upsert(record()); assert.throws(() => db.upsert(record({ message_id: '523456789012345678' }))); assert.equal(db.get('523456789012345678'), undefined); db.patch(record().message_id, { attachments: [] }); assert.equal(db.cleanupPaths().length, 1); });
test('invalid attachment set is atomic', t => { const { db } = fixture(t); db.upsert(record()); assert.throws(() => db.upsert(record({ content: 'invalid', attachments: [attachment, attachment] }))); assert.equal(db.get(record().message_id)!.content, 'original'); });
test('guild mismatch is refused', t => { const { root, db } = fixture(t); assert.throws(() => db.upsert(record({ guild_id: channel }))); assert.throws(() => new Store(join(root, 'test.sqlite3'), channel)); });
test('live/backfill cursors are separate and monotonic; events never advance them', t => { const { db } = fixture(t); db.upsert(record(), iso(), true); assert.equal(db.cursor('live', channel), undefined); db.advance('live', channel, '100'); db.advance('live', channel, '90'); db.advance('backfill', channel, '50'); assert.equal(db.cursor('live', channel), '100'); assert.equal(db.cursor('backfill', channel), '50'); });
test('run lock refuses a second collector and releases cleanly', t => { const { root } = fixture(t); const path = join(root, 'lock.sqlite3'); const a = new RunLock(path); assert.throws(() => new RunLock(path)); a.close(); new RunLock(path).close(); });
test('read-only status/export does not reset active downloads; recovery does', t => { const { root, db } = fixture(t); db.upsert(record()); db.updateAttachment(attachment.attachment_id, { status: 'downloading' }); const reader = new Store(join(root, 'test.sqlite3'), guild); assert.equal(reader.attachment(attachment.attachment_id)!.status, 'downloading'); reader.close(); db.recover(); assert.equal(db.attachment(attachment.attachment_id)!.status, 'pending'); });
test('JST date range is half-open and validates actual calendar dates', () => { assert.deepEqual(dateBounds('2026-09-14', '2026-09-15'), ['2026-09-13T15:00:00.000000+00:00', '2026-09-14T15:00:00.000000+00:00']); for (const date of ['2026-02-30', '2026-13-01', 'yesterday']) assert.throws(() => dateBounds(date, '2027-01-01')); assert.throws(() => dateBounds('2026-09-14', '2026-09-14')); });
test('JSONL preserves snake_case, deletion and date boundaries; output is unique', t => { const { root, db } = fixture(t); db.upsert(record()); db.upsert(record({ message_id: '523456789012345678', created_at: iso('2026-09-14T15:00Z'), attachments: [] })); const one = exportJsonl(db, '2026-09-14', '2026-09-15', root); assert.equal(one.count, 1); const value = JSON.parse(readFileSync(one.path, 'utf8')); assert.equal(value.message_id, record().message_id); assert.equal(value.attachments[0].attachment_id, attachment.attachment_id); db.delete(record().message_id, channel); const two = exportJsonl(db, '2026-09-14', '2026-09-15', root); assert.notEqual(one.path, two.path); assert.equal(JSON.parse(readFileSync(two.path, 'utf8')).deleted, true); });
test('config uses quoted IDs, strict flags and YAML-relative paths', t => { const { root } = fixture(t); const path = join(root, 'config.yaml'), env = join(root, '.env'); writeFileSync(env, `DISCORD_GUILD_ID=${guild}\n`); writeFileSync(path, `channels:\n  - id: "${channel}"\ncontrol:\n  mode: gateway\n`); const c = loadConfig(path, env); assert.equal(c.guild, guild); assert.equal(c.database, join(root, 'data', 'telemetry-ts.sqlite3')); writeFileSync(path, `channels:\n  - id: ${channel}\n`); assert.throws(() => loadConfig(path, env)); assert.throws(() => id(Number(channel))); });
test('scope is limited to configured guild and parent channels', () => { const c = config(''); const item = { guildId: guild, id: 'thread', parentId: channel, isThread: () => true }; assert.equal(inScope(c, item), true); assert.equal(inScope(c, { ...item, guildId: 'other' }), false); assert.equal(inScope(c, { ...item, parentId: 'other' }), false); });
test('self/bot/webhook exclusions are independent', () => { const c = config(''); assert.equal(acceptAuthor(c, 'self', { id: 'self' }, null), false); assert.equal(acceptAuthor(c, 'self', { id: 'bot', bot: true }, null), false); assert.equal(acceptAuthor({ ...c, includeWebhooks: true }, 'self', { id: 'webhook', bot: true }, 'hook'), true); assert.equal(acceptAuthor({ ...c, includeBots: true }, 'self', { id: 'webhook', bot: true }, 'hook'), false); });
test('CDN allowlist rejects redirects targets, credentials and non-HTTPS', () => { assert.equal(cdnUrl(attachment.url), true); for (const url of ['http://cdn.discordapp.com/a', 'https://cdn.discordapp.com.evil/a', 'https://user:pass@cdn.discordapp.com/a', 'https://cdn.discordapp.com:8443/a', 'file:///x']) assert.equal(cdnUrl(url), false); assert.equal(media({ ...attachment, filename: 'x.txt', content_type: 'text/plain' }), false); });
test('safe path refuses traversal and symlinks', t => { const { root } = fixture(t); assert.throws(() => safePath(root, '../outside')); assert.throws(() => safePath(root, root)); const outside = join(root, 'outside'), link = join(root, 'link'); mkdirSync(outside); symlinkSync(outside, link, 'junction'); assert.throws(() => safePath(root, 'link/file')); });
test('attachment success stores bytes using IDs, never user filename', async t => { const { root, db } = fixture(t); db.upsert(record({ attachments: [{ ...attachment, filename: '../../image.png' }] })); const c = config(root), downloads = new Attachments(c, db, async () => {}, async () => new Response('data')); downloads.pump(); await downloads.idle(); const a = db.attachment(attachment.attachment_id)!; assert.equal(a.status, 'saved'); assert.equal(readFileSync(a.path!, 'utf8'), 'data'); await downloads.close(); });
test('oversized streaming response and redirects are never stored', async t => { const { root, db } = fixture(t); for (const response of [new Response('x'.repeat(101)), new Response('', { status: 302, headers: { location: 'http://localhost' } })]) { db.upsert(record()); db.updateAttachment(attachment.attachment_id, { status: 'pending' }); const downloads = new Attachments(config(root), db, async () => {}, async () => response); downloads.pump(); await downloads.idle(); assert.ok(['failed', 'too_large'].includes(db.attachment(attachment.attachment_id)!.status!)); assert.equal(db.attachment(attachment.attachment_id)!.path, null); await downloads.close(); } });
test('delete during download cannot resurrect attachment', async t => { const { root, db } = fixture(t); db.upsert(record()); let finish!: () => void; const ready = new Promise<void>(r => { finish = r; }); const downloads = new Attachments(config(root), db, async () => {}, async () => { await ready; return new Response('data'); }); downloads.pump(); db.delete(record().message_id, channel); finish(); await downloads.idle(); assert.equal(db.attachment(attachment.attachment_id), undefined); assert.equal(existsSync(join(root, 'attachments', record().message_id, attachment.attachment_id)), false); await downloads.close(); });
test('expired attachment URL refreshes and retries with the updated URL', async t => { const { root, db } = fixture(t); db.upsert(record()); let calls = 0, refreshes = 0; const downloads = new Attachments(config(root, { retries: 1 }), db, async () => { refreshes++; db.updateAttachment(attachment.attachment_id, { url: attachment.url + '?renewed=1' }); }, async url => { calls++; if (calls === 1) return new Response('', { status: 403 }); assert.ok(String(url).endsWith('?renewed=1')); return new Response('data'); }); downloads.pump(); await downloads.idle(); assert.equal(refreshes, 1); assert.equal(db.attachment(attachment.attachment_id)!.status, 'saved'); await downloads.close(); });
