import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { meetingShell } from '../src/ui/meeting-shell';
const css = await readFile('dist/meeting.css', 'utf8');
const html = meetingShell();
await mkdir('src/generated', { recursive: true });
// Render shadcn at build time: the Worker and browser need no React runtime.
await writeFile('src/generated/meeting-ui.ts', '// Generated by pnpm run ui:build. Do not edit.\n' +
  `export const meetingCss = ${JSON.stringify(css)};\nexport const meetingHtml = ${JSON.stringify(html)};\n`);
